services:
  frontend:
    image: tunzidi/234-deploylab-frontend:latest
    pull_policy: always
    ports:
      - "8081:80"
    restart: unless-stopped
    environment:
      - VITE_GRAPHQL_URI=http://44.197.206.179:8082/graphql
      - VITE_SERVER_URI=http://44.197.206.179:8082